// Generated by scripts/gen-world-dots.mjs from Natural Earth (public domain). Do not edit.
// The dots themselves live in /public/geo/world-dots.svg (one cacheable asset).
export const WORLD_WIDTH = 1000;
export const WORLD_HEIGHT = 356;
export const WORLD_BOUNDS = { north: 72, south: -56, west: -170, east: 190 };
export const WORLD_DOTS_URL = "/geo/world-dots.svg";
