// Generated by scripts/gen-db-types.mjs from supabase/migrations. Do not edit.
// Regenerate with: npm run db:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "12" };
  public: {
    Tables: {
      access_offers: {
        Row: {
          id: string;
          title: string;
          summary: string;
          detail: string | null;
          provider_id: string | null;
          market_id: string | null;
          minimum_tier_slug: string | null;
          available_from: string | null;
          available_until: string | null;
          status: Database["public"]["Enums"]["access_offer_status"];
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          summary?: string;
          detail?: string | null;
          provider_id?: string | null;
          market_id?: string | null;
          minimum_tier_slug?: string | null;
          available_from?: string | null;
          available_until?: string | null;
          status?: Database["public"]["Enums"]["access_offer_status"];
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          summary?: string;
          detail?: string | null;
          provider_id?: string | null;
          market_id?: string | null;
          minimum_tier_slug?: string | null;
          available_from?: string | null;
          available_until?: string | null;
          status?: Database["public"]["Enums"]["access_offer_status"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "access_offers_market_id_fkey";
            columns: ["market_id"];
            isOneToOne: false;
            referencedRelation: "markets";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "access_offers_minimum_tier_slug_fkey";
            columns: ["minimum_tier_slug"];
            isOneToOne: false;
            referencedRelation: "membership_tiers";
            referencedColumns: ["slug"];
          },
          {
            foreignKeyName: "access_offers_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
        ];
      };
      ai_events: {
        Row: {
          id: string;
          kind: Database["public"]["Enums"]["ai_event_kind"];
          request_id: string | null;
          member_id: string | null;
          model: string;
          prompt_version: string;
          output: Json;
          status: Database["public"]["Enums"]["ai_review_status"];
          reviewed_by: string | null;
          reviewed_at: string | null;
          latency_ms: number | null;
          input_tokens: number | null;
          output_tokens: number | null;
          error: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          kind: Database["public"]["Enums"]["ai_event_kind"];
          request_id?: string | null;
          member_id?: string | null;
          model: string;
          prompt_version: string;
          output?: Json;
          status?: Database["public"]["Enums"]["ai_review_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          latency_ms?: number | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          error?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          kind?: Database["public"]["Enums"]["ai_event_kind"];
          request_id?: string | null;
          member_id?: string | null;
          model?: string;
          prompt_version?: string;
          output?: Json;
          status?: Database["public"]["Enums"]["ai_review_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          latency_ms?: number | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          error?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ai_events_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_events_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "requests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_events_reviewed_by_fkey";
            columns: ["reviewed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      analytics_events: {
        Row: {
          id: number;
          name: string;
          subject: string | null;
          properties: Json;
          occurred_at: string;
        };
        Insert: {
          id?: number;
          name: string;
          subject?: string | null;
          properties?: Json;
          occurred_at?: string;
        };
        Update: {
          id?: number;
          name?: string;
          subject?: string | null;
          properties?: Json;
          occurred_at?: string;
        };
        Relationships: [];
      };
      app_settings: {
        Row: {
          key: string;
          value: Json;
          description: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          description?: string | null;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          description?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      applications: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          phone: string | null;
          city: string;
          market_slug: string | null;
          occupation: string | null;
          referral_source: string | null;
          invitation_code: string | null;
          answers: Json;
          status: Database["public"]["Enums"]["application_status"];
          reviewer_id: string | null;
          decision_note: string | null;
          user_id: string | null;
          submitted_at: string;
          decided_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name: string;
          email: string;
          phone?: string | null;
          city: string;
          market_slug?: string | null;
          occupation?: string | null;
          referral_source?: string | null;
          invitation_code?: string | null;
          answers?: Json;
          status?: Database["public"]["Enums"]["application_status"];
          reviewer_id?: string | null;
          decision_note?: string | null;
          user_id?: string | null;
          submitted_at?: string;
          decided_at?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          email?: string;
          phone?: string | null;
          city?: string;
          market_slug?: string | null;
          occupation?: string | null;
          referral_source?: string | null;
          invitation_code?: string | null;
          answers?: Json;
          status?: Database["public"]["Enums"]["application_status"];
          reviewer_id?: string | null;
          decision_note?: string | null;
          user_id?: string | null;
          submitted_at?: string;
          decided_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "applications_reviewer_id_fkey";
            columns: ["reviewer_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "applications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_log: {
        Row: {
          id: number;
          actor_id: string | null;
          action: string;
          entity: string;
          entity_id: string | null;
          meta: Json;
          created_at: string;
        };
        Insert: {
          id?: number;
          actor_id?: string | null;
          action: string;
          entity: string;
          entity_id?: string | null;
          meta?: Json;
          created_at?: string;
        };
        Update: {
          id?: number;
          actor_id?: string | null;
          action?: string;
          entity?: string;
          entity_id?: string | null;
          meta?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      card_programs: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      contact_inquiries: {
        Row: {
          id: string;
          name: string;
          email: string;
          topic: string;
          message: string;
          handled: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          topic: string;
          message: string;
          handled?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          topic?: string;
          message?: string;
          handled?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      fee_rules: {
        Row: {
          id: string;
          key: string;
          label: string;
          kind: Database["public"]["Enums"]["fee_kind"];
          basis_points: number | null;
          amount_minor: number | null;
          currency: string;
          applies_to: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
          kind: Database["public"]["Enums"]["fee_kind"];
          basis_points?: number | null;
          amount_minor?: number | null;
          currency?: string;
          applies_to?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
          kind?: Database["public"]["Enums"]["fee_kind"];
          basis_points?: number | null;
          amount_minor?: number | null;
          currency?: string;
          applies_to?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      founding_members: {
        Row: {
          id: string;
          member_id: string | null;
          application_id: string | null;
          display_name: string;
          referral_source: string | null;
          relationship_owner_id: string | null;
          onboarding_status: Database["public"]["Enums"]["onboarding_status"];
          preferences_completed: boolean;
          first_request_at: string | null;
          satisfaction: number | null;
          referral_potential: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          member_id?: string | null;
          application_id?: string | null;
          display_name: string;
          referral_source?: string | null;
          relationship_owner_id?: string | null;
          onboarding_status?: Database["public"]["Enums"]["onboarding_status"];
          preferences_completed?: boolean;
          first_request_at?: string | null;
          satisfaction?: number | null;
          referral_potential?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string | null;
          application_id?: string | null;
          display_name?: string;
          referral_source?: string | null;
          relationship_owner_id?: string | null;
          onboarding_status?: Database["public"]["Enums"]["onboarding_status"];
          preferences_completed?: boolean;
          first_request_at?: string | null;
          satisfaction?: number | null;
          referral_potential?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "founding_members_application_id_fkey";
            columns: ["application_id"];
            isOneToOne: false;
            referencedRelation: "applications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "founding_members_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "founding_members_relationship_owner_id_fkey";
            columns: ["relationship_owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      founding_providers: {
        Row: {
          id: string;
          provider_id: string;
          vetting_status: string;
          terms_status: string;
          test_request_status: string;
          performance_note: string | null;
          preferred_status: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          provider_id: string;
          vetting_status?: string;
          terms_status?: string;
          test_request_status?: string;
          performance_note?: string | null;
          preferred_status?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          provider_id?: string;
          vetting_status?: string;
          terms_status?: string;
          test_request_status?: string;
          performance_note?: string | null;
          preferred_status?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "founding_providers_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
        ];
      };
      invitations: {
        Row: {
          id: string;
          inviter_id: string | null;
          email: string | null;
          invitee_name: string | null;
          code_hash: string;
          code_hint: string;
          status: Database["public"]["Enums"]["invitation_status"];
          application_id: string | null;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          inviter_id?: string | null;
          email?: string | null;
          invitee_name?: string | null;
          code_hash: string;
          code_hint: string;
          status?: Database["public"]["Enums"]["invitation_status"];
          application_id?: string | null;
          expires_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          inviter_id?: string | null;
          email?: string | null;
          invitee_name?: string | null;
          code_hash?: string;
          code_hint?: string;
          status?: Database["public"]["Enums"]["invitation_status"];
          application_id?: string | null;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "invitations_application_id_fkey";
            columns: ["application_id"];
            isOneToOne: false;
            referencedRelation: "applications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invitations_inviter_id_fkey";
            columns: ["inviter_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      journey_items: {
        Row: {
          id: string;
          journey_id: string;
          request_id: string | null;
          kind: Database["public"]["Enums"]["journey_item_kind"];
          title: string;
          detail: string | null;
          location: string | null;
          starts_at: string | null;
          ends_at: string | null;
          timezone: string | null;
          status: Database["public"]["Enums"]["journey_item_status"];
          sort_order: number;
        };
        Insert: {
          id?: string;
          journey_id: string;
          request_id?: string | null;
          kind: Database["public"]["Enums"]["journey_item_kind"];
          title: string;
          detail?: string | null;
          location?: string | null;
          starts_at?: string | null;
          ends_at?: string | null;
          timezone?: string | null;
          status?: Database["public"]["Enums"]["journey_item_status"];
          sort_order?: number;
        };
        Update: {
          id?: string;
          journey_id?: string;
          request_id?: string | null;
          kind?: Database["public"]["Enums"]["journey_item_kind"];
          title?: string;
          detail?: string | null;
          location?: string | null;
          starts_at?: string | null;
          ends_at?: string | null;
          timezone?: string | null;
          status?: Database["public"]["Enums"]["journey_item_status"];
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "journey_items_journey_id_fkey";
            columns: ["journey_id"];
            isOneToOne: false;
            referencedRelation: "journeys";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "journey_items_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "requests";
            referencedColumns: ["id"];
          },
        ];
      };
      journeys: {
        Row: {
          id: string;
          member_id: string;
          title: string;
          summary: string | null;
          status: Database["public"]["Enums"]["journey_status"];
          starts_on: string | null;
          ends_on: string | null;
          primary_market_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          member_id: string;
          title: string;
          summary?: string | null;
          status?: Database["public"]["Enums"]["journey_status"];
          starts_on?: string | null;
          ends_on?: string | null;
          primary_market_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string;
          title?: string;
          summary?: string | null;
          status?: Database["public"]["Enums"]["journey_status"];
          starts_on?: string | null;
          ends_on?: string | null;
          primary_market_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "journeys_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "journeys_primary_market_id_fkey";
            columns: ["primary_market_id"];
            isOneToOne: false;
            referencedRelation: "markets";
            referencedColumns: ["id"];
          },
        ];
      };
      markets: {
        Row: {
          id: string;
          slug: string;
          name: string;
          region: string;
          timezone: string;
          currency: string;
          status: Database["public"]["Enums"]["market_status"];
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          region: string;
          timezone: string;
          currency?: string;
          status?: Database["public"]["Enums"]["market_status"];
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          region?: string;
          timezone?: string;
          currency?: string;
          status?: Database["public"]["Enums"]["market_status"];
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      member_cards: {
        Row: {
          id: string;
          member_id: string;
          program_id: string;
          status: Database["public"]["Enums"]["card_status"];
          last_four: string | null;
          requested_at: string | null;
          issued_at: string | null;
        };
        Insert: {
          id?: string;
          member_id: string;
          program_id: string;
          status?: Database["public"]["Enums"]["card_status"];
          last_four?: string | null;
          requested_at?: string | null;
          issued_at?: string | null;
        };
        Update: {
          id?: string;
          member_id?: string;
          program_id?: string;
          status?: Database["public"]["Enums"]["card_status"];
          last_four?: string | null;
          requested_at?: string | null;
          issued_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "member_cards_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "member_cards_program_id_fkey";
            columns: ["program_id"];
            isOneToOne: false;
            referencedRelation: "card_programs";
            referencedColumns: ["id"];
          },
        ];
      };
      member_people: {
        Row: {
          id: string;
          member_id: string;
          name: string;
          relationship: string;
          notes: string | null;
          birthday: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          member_id: string;
          name: string;
          relationship: string;
          notes?: string | null;
          birthday?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string;
          name?: string;
          relationship?: string;
          notes?: string | null;
          birthday?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "member_people_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      member_preferences: {
        Row: {
          id: string;
          member_id: string;
          domain: Database["public"]["Enums"]["preference_domain"];
          label: string;
          value: string;
          source: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          member_id: string;
          domain: Database["public"]["Enums"]["preference_domain"];
          label: string;
          value: string;
          source?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string;
          domain?: Database["public"]["Enums"]["preference_domain"];
          label?: string;
          value?: string;
          source?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "member_preferences_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      membership_tiers: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          annual_fee_minor: number | null;
          initiation_fee_minor: number | null;
          currency: string;
          invitation_allowance: number;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string;
          annual_fee_minor?: number | null;
          initiation_fee_minor?: number | null;
          currency?: string;
          invitation_allowance?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          annual_fee_minor?: number | null;
          initiation_fee_minor?: number | null;
          currency?: string;
          invitation_allowance?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      memberships: {
        Row: {
          id: string;
          member_id: string;
          tier_id: string;
          status: Database["public"]["Enums"]["membership_status"];
          member_number: string;
          started_at: string | null;
          renews_at: string | null;
          relationship_owner_id: string | null;
          is_founding: boolean;
          organization_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          member_id: string;
          tier_id: string;
          status?: Database["public"]["Enums"]["membership_status"];
          member_number?: string;
          started_at?: string | null;
          renews_at?: string | null;
          relationship_owner_id?: string | null;
          is_founding?: boolean;
          organization_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string;
          tier_id?: string;
          status?: Database["public"]["Enums"]["membership_status"];
          member_number?: string;
          started_at?: string | null;
          renews_at?: string | null;
          relationship_owner_id?: string | null;
          is_founding?: boolean;
          organization_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "memberships_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "memberships_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "memberships_relationship_owner_id_fkey";
            columns: ["relationship_owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "memberships_tier_id_fkey";
            columns: ["tier_id"];
            isOneToOne: false;
            referencedRelation: "membership_tiers";
            referencedColumns: ["id"];
          },
        ];
      };
      notification_templates: {
        Row: {
          id: string;
          key: string;
          channel: Database["public"]["Enums"]["notification_channel"];
          subject: string | null;
          body: string;
          is_active: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          channel: Database["public"]["Enums"]["notification_channel"];
          subject?: string | null;
          body: string;
          is_active?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          channel?: Database["public"]["Enums"]["notification_channel"];
          subject?: string | null;
          body?: string;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          kind: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          kind?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          kind?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      partner_applications: {
        Row: {
          id: string;
          organization: string;
          contact_name: string;
          email: string;
          phone: string | null;
          category_slug: string | null;
          city: string;
          website: string | null;
          message: string;
          status: string;
          submitted_at: string;
        };
        Insert: {
          id?: string;
          organization: string;
          contact_name: string;
          email: string;
          phone?: string | null;
          category_slug?: string | null;
          city: string;
          website?: string | null;
          message: string;
          status?: string;
          submitted_at?: string;
        };
        Update: {
          id?: string;
          organization?: string;
          contact_name?: string;
          email?: string;
          phone?: string | null;
          category_slug?: string | null;
          city?: string;
          website?: string | null;
          message?: string;
          status?: string;
          submitted_at?: string;
        };
        Relationships: [];
      };
      privileges: {
        Row: {
          id: string;
          tier_id: string;
          title: string;
          description: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          tier_id: string;
          title: string;
          description?: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          tier_id?: string;
          title?: string;
          description?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "privileges_tier_id_fkey";
            columns: ["tier_id"];
            isOneToOne: false;
            referencedRelation: "membership_tiers";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          preferred_name: string | null;
          phone: string | null;
          role: Database["public"]["Enums"]["app_role"];
          timezone: string;
          home_market_id: string | null;
          organization_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string;
          preferred_name?: string | null;
          phone?: string | null;
          role?: Database["public"]["Enums"]["app_role"];
          timezone?: string;
          home_market_id?: string | null;
          organization_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          preferred_name?: string | null;
          phone?: string | null;
          role?: Database["public"]["Enums"]["app_role"];
          timezone?: string;
          home_market_id?: string | null;
          organization_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_home_market_id_fkey";
            columns: ["home_market_id"];
            isOneToOne: false;
            referencedRelation: "markets";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "profiles_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      providers: {
        Row: {
          id: string;
          name: string;
          category_slug: string | null;
          market_id: string | null;
          status: Database["public"]["Enums"]["provider_status"];
          is_founding: boolean;
          website: string | null;
          contact_name: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          terms_summary: string | null;
          notes: string | null;
          test_request_status: string;
          performance_score: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category_slug?: string | null;
          market_id?: string | null;
          status?: Database["public"]["Enums"]["provider_status"];
          is_founding?: boolean;
          website?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          terms_summary?: string | null;
          notes?: string | null;
          test_request_status?: string;
          performance_score?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category_slug?: string | null;
          market_id?: string | null;
          status?: Database["public"]["Enums"]["provider_status"];
          is_founding?: boolean;
          website?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          terms_summary?: string | null;
          notes?: string | null;
          test_request_status?: string;
          performance_score?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "providers_category_slug_fkey";
            columns: ["category_slug"];
            isOneToOne: false;
            referencedRelation: "request_categories";
            referencedColumns: ["slug"];
          },
          {
            foreignKeyName: "providers_market_id_fkey";
            columns: ["market_id"];
            isOneToOne: false;
            referencedRelation: "markets";
            referencedColumns: ["id"];
          },
        ];
      };
      request_categories: {
        Row: {
          id: string;
          slug: string;
          name: string;
          vertical: Database["public"]["Enums"]["vertical"];
          is_active: boolean;
          sort_order: number;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          vertical?: Database["public"]["Enums"]["vertical"];
          is_active?: boolean;
          sort_order?: number;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          vertical?: Database["public"]["Enums"]["vertical"];
          is_active?: boolean;
          sort_order?: number;
        };
        Relationships: [];
      };
      request_events: {
        Row: {
          id: string;
          request_id: string;
          kind: string;
          from_status: Database["public"]["Enums"]["request_status"] | null;
          to_status: Database["public"]["Enums"]["request_status"] | null;
          actor_id: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          request_id: string;
          kind: string;
          from_status?: Database["public"]["Enums"]["request_status"] | null;
          to_status?: Database["public"]["Enums"]["request_status"] | null;
          actor_id?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          request_id?: string;
          kind?: string;
          from_status?: Database["public"]["Enums"]["request_status"] | null;
          to_status?: Database["public"]["Enums"]["request_status"] | null;
          actor_id?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "request_events_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "request_events_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "requests";
            referencedColumns: ["id"];
          },
        ];
      };
      request_messages: {
        Row: {
          id: string;
          request_id: string;
          author_id: string | null;
          author_kind: Database["public"]["Enums"]["message_author_kind"];
          author_name: string;
          body: string;
          visibility: Database["public"]["Enums"]["message_visibility"];
          created_at: string;
        };
        Insert: {
          id?: string;
          request_id: string;
          author_id?: string | null;
          author_kind: Database["public"]["Enums"]["message_author_kind"];
          author_name?: string;
          body: string;
          visibility?: Database["public"]["Enums"]["message_visibility"];
          created_at?: string;
        };
        Update: {
          id?: string;
          request_id?: string;
          author_id?: string | null;
          author_kind?: Database["public"]["Enums"]["message_author_kind"];
          author_name?: string;
          body?: string;
          visibility?: Database["public"]["Enums"]["message_visibility"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "request_messages_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "request_messages_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "requests";
            referencedColumns: ["id"];
          },
        ];
      };
      request_options: {
        Row: {
          id: string;
          request_id: string;
          provider_id: string | null;
          title: string;
          summary: string;
          price_minor: number | null;
          price_currency: string | null;
          status: Database["public"]["Enums"]["option_status"];
          expires_at: string | null;
          responded_at: string | null;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          request_id: string;
          provider_id?: string | null;
          title: string;
          summary?: string;
          price_minor?: number | null;
          price_currency?: string | null;
          status?: Database["public"]["Enums"]["option_status"];
          expires_at?: string | null;
          responded_at?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          request_id?: string;
          provider_id?: string | null;
          title?: string;
          summary?: string;
          price_minor?: number | null;
          price_currency?: string | null;
          status?: Database["public"]["Enums"]["option_status"];
          expires_at?: string | null;
          responded_at?: string | null;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "request_options_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "request_options_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "requests";
            referencedColumns: ["id"];
          },
        ];
      };
      requests: {
        Row: {
          id: string;
          reference: string;
          member_id: string;
          category_slug: string | null;
          vertical: Database["public"]["Enums"]["vertical"];
          title: string;
          brief: string;
          status: Database["public"]["Enums"]["request_status"];
          priority: Database["public"]["Enums"]["request_priority"];
          market_id: string | null;
          assignee_id: string | null;
          starts_at: string | null;
          ends_at: string | null;
          timezone: string | null;
          party_size: number | null;
          budget_minor: number | null;
          budget_currency: string | null;
          location: string | null;
          first_response_due_at: string | null;
          first_responded_at: string | null;
          journey_id: string | null;
          details: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reference?: string;
          member_id: string;
          category_slug?: string | null;
          vertical?: Database["public"]["Enums"]["vertical"];
          title: string;
          brief: string;
          status?: Database["public"]["Enums"]["request_status"];
          priority?: Database["public"]["Enums"]["request_priority"];
          market_id?: string | null;
          assignee_id?: string | null;
          starts_at?: string | null;
          ends_at?: string | null;
          timezone?: string | null;
          party_size?: number | null;
          budget_minor?: number | null;
          budget_currency?: string | null;
          location?: string | null;
          first_response_due_at?: string | null;
          first_responded_at?: string | null;
          journey_id?: string | null;
          details?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          reference?: string;
          member_id?: string;
          category_slug?: string | null;
          vertical?: Database["public"]["Enums"]["vertical"];
          title?: string;
          brief?: string;
          status?: Database["public"]["Enums"]["request_status"];
          priority?: Database["public"]["Enums"]["request_priority"];
          market_id?: string | null;
          assignee_id?: string | null;
          starts_at?: string | null;
          ends_at?: string | null;
          timezone?: string | null;
          party_size?: number | null;
          budget_minor?: number | null;
          budget_currency?: string | null;
          location?: string | null;
          first_response_due_at?: string | null;
          first_responded_at?: string | null;
          journey_id?: string | null;
          details?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "requests_assignee_id_fkey";
            columns: ["assignee_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "requests_category_slug_fkey";
            columns: ["category_slug"];
            isOneToOne: false;
            referencedRelation: "request_categories";
            referencedColumns: ["slug"];
          },
          {
            foreignKeyName: "requests_journey_id_fkey";
            columns: ["journey_id"];
            isOneToOne: false;
            referencedRelation: "journeys";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "requests_market_id_fkey";
            columns: ["market_id"];
            isOneToOne: false;
            referencedRelation: "markets";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "requests_member_id_fkey";
            columns: ["member_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      service_level_targets: {
        Row: {
          priority: Database["public"]["Enums"]["request_priority"];
          first_response_minutes: number;
          options_within_hours: number;
        };
        Insert: {
          priority: Database["public"]["Enums"]["request_priority"];
          first_response_minutes: number;
          options_within_hours: number;
        };
        Update: {
          priority?: Database["public"]["Enums"]["request_priority"];
          first_response_minutes?: number;
          options_within_hours?: number;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      check_invitation: { Args: { code: string }; Returns: boolean };
      current_app_role: {
        Args: Record<PropertyKey, never>;
        Returns: Database["public"]["Enums"]["app_role"];
      };
      has_active_membership: { Args: { uid: string }; Returns: boolean };
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean };
      is_staff: { Args: Record<PropertyKey, never>; Returns: boolean };
      member_cancel_request: { Args: { target: string; reason?: string }; Returns: undefined };
      member_issue_invitation: {
        Args: { invitee_email: string; invitee_name: string };
        Returns: { invitation_id: string; code: string }[];
      };
      member_respond_to_option: {
        Args: { option_id: string; decision: string };
        Returns: Database["public"]["Enums"]["option_status"];
      };
    };
    Enums: {
      access_offer_status: "draft" | "published" | "archived";
      ai_event_kind: "intent_extraction" | "clarification" | "summary";
      ai_review_status: "proposed" | "accepted" | "edited" | "dismissed" | "failed";
      app_role: "applicant" | "member" | "concierge" | "admin" | "provider";
      application_status:
        | "submitted"
        | "in_review"
        | "conversation"
        | "approved"
        | "waitlisted"
        | "declined"
        | "withdrawn";
      card_status: "not_issued" | "requested" | "in_production" | "issued" | "suspended";
      fee_kind: "percentage" | "fixed";
      invitation_status: "issued" | "accepted" | "expired" | "revoked";
      journey_item_kind:
        "flight" | "stay" | "dining" | "transfer" | "experience" | "event" | "note";
      journey_item_status: "tentative" | "confirmed" | "cancelled";
      journey_status: "planning" | "confirmed" | "underway" | "completed" | "cancelled";
      market_status: "planned" | "preparing" | "active" | "paused";
      membership_status: "pending_activation" | "active" | "paused" | "lapsed" | "cancelled";
      message_author_kind: "member" | "concierge" | "system" | "ai";
      message_visibility: "member" | "internal";
      notification_channel: "email" | "sms" | "push";
      onboarding_status:
        "not_started" | "welcome_call" | "preferences" | "first_request" | "established";
      option_status: "draft" | "presented" | "accepted" | "declined" | "expired" | "withdrawn";
      preference_domain:
        | "travel"
        | "stays"
        | "dining"
        | "wellness"
        | "family"
        | "communication"
        | "gifting"
        | "other";
      provider_status: "prospect" | "vetting" | "approved" | "preferred" | "paused" | "removed";
      request_priority: "standard" | "priority" | "urgent";
      request_status:
        | "received"
        | "clarifying"
        | "sourcing"
        | "options_ready"
        | "confirmed"
        | "in_progress"
        | "completed"
        | "cancelled";
      vertical: "concierge" | "aviation" | "residences" | "private" | "enterprise";
    };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"];
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T];
